env:
  browser: true
  es6: true
  node: true

extends:
  - 'standard'

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: 2019
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  eqeqeq:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
      - time
  no-var:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  complexity:
    - warn
    - 10
